// Generated by Wrangler on Tue Apr 09 2024 17:36:03 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	GROQ_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	DRUVIS_DB: D1Database;
}
