// Generated by Wrangler on Wed May 01 2024 23:07:15 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	USE_TRANSLATION: string;
	GROQ_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	OPENAI_API_KEY: string;
	DRUVIS_DB: D1Database;
}
