// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm build-cf-types`
// biome-ignore lint/complexity/noBannedTypes: this file is generated file
type Env = {};
